version: '3.1'
services:
  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: kafka
    ports:
      - "9092:9092"
      - "9093:9093"
    environment:
      CLUSTER_ID: 4L6g3nShT-eMCtK--X86sw
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
      # KRaft mode configuration
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_NODE_ID: 1
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka:9093'
      KAFKA_LISTENERS: PLAINTEXT://kafka:9092,CONTROLLER://kafka:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_LOG_DIRS: '/tmp/kraft-combined-logs'
      # Reduce metadata logging verbosity
      KAFKA_LOG4J_LOGGERS: "org.apache.kafka.metadata.MetadataLoader=WARN,org.apache.kafka.controller=WARN"
      KAFKA_LOG4J_ROOT_LOGLEVEL: INFO
    # volumes:
    #   - ./kafka-data:/tmp/kraft-combined-logs
    networks:
      - enable-event-driven-network

  kafka-ui:
    image: kafbat/kafka-ui:latest
    container_name: kafka-ui
    restart: unless-stopped
    depends_on:
      - kafka
    ports:
      - "8080:8080"
    environment:
      DYNAMIC_CONFIG_ENABLED: 'true'
      KAFKA_CLUSTERS_0_NAME: kafka-cluster
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9092
      KAFKA_CLUSTERS_0_PROPERTIES_SECURITY_PROTOCOL: PLAINTEXT
    networks:
      - enable-event-driven-network

  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    hostname: mssql-server
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Passw0rd
      MSSQL_PID: Developer
      MSSQL_AGENT_ENABLED: true # Important for Debezium SQL Server connector
    # volumes:
    #   - ./mssql-data:/var/opt/mssql
    networks:
      - enable-event-driven-network
  
  debezium-kafka-connect:
    image: quay.io/debezium/connect:3.2.3.Final
    container_name: debezium-kafka-connect
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: 'kafka:9092'
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: 'enable_event_driven_connect_configs'
      OFFSET_STORAGE_TOPIC: 'enable_event_driven_connect_offsets'
      STATUS_STORAGE_TOPIC: 'enable_event_driven_connect_statuses'
      ENABLE_APICURIO_CONVERTERS: true
    depends_on:
      - kafka
      - mssql-server
    networks:
      - enable-event-driven-network

networks:
  enable-event-driven-network:
    driver: bridge
