version: '3.1'
services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.4.0
    hostname: zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    networks:
      - enable-event-driven-network

  kafka:
    image: confluentinc/cp-kafka:7.4.0
    hostname: kafka
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9101:9101"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_JMX_PORT: 9101
      KAFKA_JMX_HOSTNAME: localhost
    networks:
      - enable-event-driven-network

  kafdrop:
    image: obsidiandynamics/kafdrop
    container_name: kafdrop
    ports:
      - 9000:9000
    environment:
      KAFKA_BROKERCONNECT: 'kafka:29092'
    depends_on:
      - kafka
    networks:
      - enable-event-driven-network

  mssql-server:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: mssql-server
    hostname: mssql-server
    ports:
      - "1433:1433"
    environment:
      ACCEPT_EULA: Y
      SA_PASSWORD: Passw0rd
      MSSQL_PID: Developer
      MSSQL_AGENT_ENABLED: true # Important for Debezium SQL Server connector
    volumes:
      - ./mssql-data:/var/opt/mssql
    networks:
      - enable-event-driven-network
  
  debezium-kafka-connect:
    image: quay.io/debezium/connect:3.2.3.Final
    container_name: debezium-kafka-connect
    ports:
      - 8083:8083
    environment:
      BOOTSTRAP_SERVERS: 'kafka:29092'
      GROUP_ID: 1
      CONFIG_STORAGE_TOPIC: 'enable_event_driven_connect_configs'
      OFFSET_STORAGE_TOPIC: 'enable_event_driven_connect_offsets'
      STATUS_STORAGE_TOPIC: 'enable_event_driven_connect_statuses'
      ENABLE_APICURIO_CONVERTERS: true
    depends_on:
      - kafka
      - mssql-server
    networks:
      - enable-event-driven-network

networks:
  enable-event-driven-network:
    driver: bridge
